import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import SpotCard from "../components/SpotCard";
import { trpc } from "../utils/trpc";

import SpotContainer from "../components/SpotContainer";

const Home: NextPage = () => {

  const {data, isLoading, error} = trpc.spot.getSpots.useQuery();

  console.log(data);

  return (
    <>
      <Head>
        <title>Recur</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center flex-col">
        {/* {
          isLoading
          ? <>Loading</>
          :<SpotContainer spots={data} />
        } */}
      {/* <button onClick={() => signIn()}>Sign In</button> */}
      </main>
    </>
  );
};

export default Home;

