import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import SpotContainer from "../components/SpotContainer";

const Home: NextPage = () => {
  const { data, isLoading, error } = trpc.spot.getSpots.useQuery({ limit: 10 });

  return (
    <>
      <Head>
        <title>Recur</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col items-center text-gray-200">
        {error && (
          <div>
            <div className="flex h-10 w-screen items-center justify-center bg-red-600 font-semibold">
              {error.message}
            </div>
          </div>
        )}
        {isLoading ? (
          <>Loading</>
        ) : data ? (
          <SpotContainer spots={data} />
        ) : (
          <></>
        )}
      </main>
    </>
  );
};

export default Home;
