import { type NextPage } from "next";
import Head from "next/head";
import SpotCard from "../components/SpotCard";
import { trpc } from "../utils/trpc";

import SpotContainer from "../components/SpotContainer";

const Home: NextPage = () => {

  const {data, isLoading, error} = trpc.spot.getSpots.useQuery();

  return (
    <>
      <Head>
        <title>Recur</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full items-center flex-col">
        {
          isLoading
          ? <>Loading</>
          :<SpotContainer spots={data} />
        }
      </main>
    </>
  );
};

export default Home;

